### PR TITLE
Add custom notification icon support

### PR DESCRIPTION
**Pull request by jarifibrahim**
I was not able to test the code on my machine. Please run it and comment the results. Thanks.

### CODE REVIEW

**Comment by jarifibrahim** [comment]
Would it be better if the user could set all options at once instead of just the icon?
Something like `logger.options` could be set by the user. Options would include `icon` and other settings. https://github.com/hkirat/notification-logger/issues/10

**Comment by hkirat** [comment]
Looks like a good fix. 
I think including something like logger.options is a good idea. 
A constructor function to set the options in the beginning would also be nice. 
(Something like logger.init(icon) )
Could you elaborate on what options you would like to include other than icon?

**Comment by jarifibrahim** [comment]
All the options listed here [0] could be used.
[0] - https://developer.mozilla.org/en-US/docs/Web/API/Notification/Notification

There's one more thing. Currently `logger.icon` is directly accessible. The user can change icon without calling `modifyIcon` function. Is there any way to restrict this ?

**Comment by hkirat** [comment]
I am merging this as it is for now.
Later we can modify for adding options as well
Also, logger.icon will become inaccessible once you don't define it inside window.logger

**Pull request merged**
