### PR TITLE
Clean out dup function and reminify.

### PR DESCRIPTION
**Pull request by danielmcgraw**
Removed genericLogger, looks to be a dup of log and never called. Recompressed after the change to make sure that it didn't stick around in the minified version.

### CODE REVIEW

**Comment by hkirat** [comment]
Hi,
Turns out genericLogger was a redundant function.
I love what you've done to the js file.
But I'm a bit worried about the minified file. It would be great if you would preserve the variable and function names in the minified file. Just make this change and I'll merge.
Thanks

**Comment by hkirat** [comment]
any update @danielmcgraw

**Comment by danielmcgraw** [comment]
Correct me if I'm wrong, but it looks like you already have a min file that has names and vars that are minified so this should be about the same. We could do a whitespace only minification if you'd prefer?

**Comment by hkirat** [comment]
Yup seems so.
Sorry for the confusion.

**Pull request merged**
